version: 2

jobs:
  build:
    working_directory: ~/converter
    docker:
      - image: circleci/node:6.14-stretch
    steps:
      - checkout
      - run:
          name: install grunt
          command: |
            sudo npm install -g grunt-cli
      - run:
          name: install npm dependencies
          command: |
            npm install --dev
      - run:
          name: run tests
          command: |
            grunt coveralls

